# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:15:18+00:00

from __future__ import annotations

from enum import Enum


class Format(Enum):
    json = 'json'
    xml = 'xml'


class Status(Enum):
    ALL = 'ALL'
    ACTIVE = 'ACTIVE'
    ARCHIVED = 'ARCHIVED'


class EventType(Enum):
    CONSTRUCTION = 'CONSTRUCTION'
    SPECIAL_EVENT = 'SPECIAL_EVENT'
    INCIDENT = 'INCIDENT'
    WEATHER_CONDITION = 'WEATHER_CONDITION'
    ROAD_CONDITION = 'ROAD_CONDITION'
